version: '2.2'

services:
  database:
    build: ./database/
    image: vmm-database
  app:
    build: .
    image: vmm-app
    ports:
      - "3000:3000"
    volumes: 
      - "${PWD}:/app"
    links:
      - database
